site_name: CivicDMV
site_url: https://civicdmv-handbook.readthedocs.io/en/latest/

repo_url: https://github.com/civicdmv/handbook/

theme:
    name: readthedocs

extra_css:
    - css/extra.css

plugins:
    - search
    
pages:
    - Welcome: README.md
    - About: about.md
    - Contribute: contribute.md
    - Principles: principles.md
    - Standards: standards.md
    - Projects: projects.md    
    - Roadmap: roadmap.md
    - Community: community.md
    - Calendar: calendar.md    
    - Connect: connect.md
    - Ops: ops.md
    - Conduct: conduct.md    
    - Licensing: licensing.md    
    - Colophon: colophon.md
    - Help: help.md
